//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClassLibraryEF
{
    using System;
    using System.Collections.Generic;
    
    public partial class ContentTable
    {
        public int Id { get; set; }
        public byte[] ImagePath { get; set; }
        public string SportDetail { get; set; }
        public string FullDetail { get; set; }
        public string Title { get; set; }
        public int IdSport { get; set; }
    
        public virtual TypeSport TypeSport { get; set; }
    }
}
